In [3]:
!pip install pandasql -i https://artifactory.apps.bancolombia.com/api/pypi/python-org/simple --trusted-host artifactory.apps.bancolombia.com

Looking in indexes: https://artifactory.apps.bancolombia.com/api/pypi/python-org/simple
Collecting pandasql
  Downloading https://artifactory.apps.bancolombia.com/api/pypi/python-org/packages/packages/6b/c4/ee4096ffa2eeeca0c749b26f0371bd26aa5c8b611c43de99a4f86d3de0a7/pandasql-0.7.3.tar.gz
Requirement already satisfied: numpy in c:\users\ducatano\appdata\local\continuum\anaconda3\lib\site-packages (from pandasql) (1.15.4)
Requirement already satisfied: pandas in c:\users\ducatano\appdata\local\continuum\anaconda3\lib\site-packages (from pandasql) (0.23.4)
Requirement already satisfied: sqlalchemy in c:\users\ducatano\appdata\local\continuum\anaconda3\lib\site-packages (from pandasql) (1.2.15)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\ducatano\appdata\local\continuum\anaconda3\lib\site-packages (from pandas->pandasql) (2.7.5)
Requirement already satisfied: pytz>=2011k in c:\users\ducatano\appdata\local\continuum\anaconda3\lib\site-packages (from pandas->pandasql) (2018.7)
Requirement already satisfied: six>=1.5 in c:\users\ducatano\appdata\local\continuum\anaconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas->pandasql) (1.12.0)
Building wheels for collected packages: pandasql
  Running setup.py bdist_wheel for pandasql: started
  Running setup.py bdist_wheel for pandasql: finished with status 'done'
  Stored in directory: C:\Users\ducatano\AppData\Local\pip\Cache\wheels\3b\07\4b\c967e15e7353fcc5ff90c99582410e422e2407ead7465055c6
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [4]:
from pandasql import sqldf
import pandas as pd
from sklearn.datasets import load_iris
from pandasql import sqldf
from pandasql import load_meat, load_births
import re

In [5]:
#Cargar las tres datas
births = load_births()
meat = load_meat()
iris = load_iris()

In [6]:
#creamos dataframe (es una estructura de datos tabular bidimensional de tamaño variable y potencialmente heterogénea con ejes etiquetados (filas y columnas).)
iris_df = pd.DataFrame(iris.data, columns=["Petal length","Petal Width","Sepal Length","Sepal Width"])

## Categorical. from_codes.
Haga un tipo categórico a partir de códigos y categorías o dtype. Este constructor es útil si ya tiene códigos y categorías / dtype y,por lo tanto, no necesita el paso de factorización (computación intensiva), que generalmente se realiza en el constructor.

In [7]:
iris_df

     Petal length  Petal Width  Sepal Length  Sepal Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
5             5.4          3.9           1.7          0.4
6             4.6          3.4           1.4          0.3
7             5.0          3.4           1.5          0.2
8             4.4          2.9           1.4          0.2
9             4.9          3.1           1.5          0.1
10            5.4          3.7           1.5          0.2
11            4.8          3.4           1.6          0.2
12            4.8          3.0           1.4          0.1
13            4.3          3.0           1.1          0.1
14            5.8          4.0           1.2          0.2
15            5.7          4.4           1.5          0.4
16            5.4          3.9           1.3          0.4
17            5.1          3.5           1.4          0.3
18            5.7          3.8           1.7          0.3
19            5.1          3.8           1.5          0.3
20            5.4          3.4           1.7          0.2
21            5.1          3.7           1.5          0.4
22            4.6          3.6           1.0          0.2
23            5.1          3.3           1.7          0.5
24            4.8          3.4           1.9          0.2
25            5.0          3.0           1.6          0.2
26            5.0          3.4           1.6          0.4
27            5.2          3.5           1.5          0.2
28            5.2          3.4           1.4          0.2
29            4.7          3.2           1.6          0.2
..            ...          ...           ...          ...
120           6.9          3.2           5.7          2.3
121           5.6          2.8           4.9          2.0
122           7.7          2.8           6.7          2.0
123           6.3          2.7           4.9          1.8
124           6.7          3.3           5.7          2.1
125           7.2          3.2           6.0          1.8
126           6.2          2.8           4.8          1.8
127           6.1          3.0           4.9          1.8
128           6.4          2.8           5.6          2.1
129           7.2          3.0           5.8          1.6
130           7.4          2.8           6.1          1.9
131           7.9          3.8           6.4          2.0
132           6.4          2.8           5.6          2.2
133           6.3          2.8           5.1          1.5
134           6.1          2.6           5.6          1.4
135           7.7          3.0           6.1          2.3
136           6.3          3.4           5.6          2.4
137           6.4          3.1           5.5          1.8
138           6.0          3.0           4.8          1.8
139           6.9          3.1           5.4          2.1
140           6.7          3.1           5.6          2.4
141           6.9          3.1           5.1          2.3
142           5.8          2.7           5.1          1.9
143           6.8          3.2           5.9          2.3
144           6.7          3.3           5.7          2.5
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [8]:
#‘target_names’, the meaning of the labels
#Si necesita la etiqueta de cadena puede usar target_names y agregue una nueva columna llamada species:
iris_df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

In [13]:
iris_df

     Petallength  PetalWidth  SepalLength  SepalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
5            5.4         3.9          1.7         0.4     setosa
6            4.6         3.4          1.4         0.3     setosa
7            5.0         3.4          1.5         0.2     setosa
8            4.4         2.9          1.4         0.2     setosa
9            4.9         3.1          1.5         0.1     setosa
10           5.4         3.7          1.5         0.2     setosa
11           4.8         3.4          1.6         0.2     setosa
12           4.8         3.0          1.4         0.1     setosa
13           4.3         3.0          1.1         0.1     setosa
14           5.8         4.0          1.2         0.2     setosa
15           5.7         4.4          1.5         0.4     setosa
16           5.4         3.9          1.3         0.4     setosa
17           5.1         3.5          1.4         0.3     setosa
18           5.7         3.8          1.7         0.3     setosa
19           5.1         3.8          1.5         0.3     setosa
20           5.4         3.4          1.7         0.2     setosa
21           5.1         3.7          1.5         0.4     setosa
22           4.6         3.6          1.0         0.2     setosa
23           5.1         3.3          1.7         0.5     setosa
24           4.8         3.4          1.9         0.2     setosa
25           5.0         3.0          1.6         0.2     setosa
26           5.0         3.4          1.6         0.4     setosa
27           5.2         3.5          1.5         0.2     setosa
28           5.2         3.4          1.4         0.2     setosa
29           4.7         3.2          1.6         0.2     setosa
..           ...         ...          ...         ...        ...
120          6.9         3.2          5.7         2.3  virginica
121          5.6         2.8          4.9         2.0  virginica
122          7.7         2.8          6.7         2.0  virginica
123          6.3         2.7          4.9         1.8  virginica
124          6.7         3.3          5.7         2.1  virginica
125          7.2         3.2          6.0         1.8  virginica
126          6.2         2.8          4.8         1.8  virginica
127          6.1         3.0          4.9         1.8  virginica
128          6.4         2.8          5.6         2.1  virginica
129          7.2         3.0          5.8         1.6  virginica
130          7.4         2.8          6.1         1.9  virginica
131          7.9         3.8          6.4         2.0  virginica
132          6.4         2.8          5.6         2.2  virginica
133          6.3         2.8          5.1         1.5  virginica
134          6.1         2.6          5.6         1.4  virginica
135          7.7         3.0          6.1         2.3  virginica
136          6.3         3.4          5.6         2.4  virginica
137          6.4         3.1          5.5         1.8  virginica
138          6.0         3.0          4.8         1.8  virginica
139          6.9         3.1          5.4         2.1  virginica
140          6.7         3.1          5.6         2.4  virginica
141          6.9         3.1          5.1         2.3  virginica
142          5.8         2.7          5.1         1.9  virginica
143          6.8         3.2          5.9         2.3  virginica
144          6.7         3.3          5.7         2.5  virginica
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [17]:
#Salvavidas
iris_df.columns = [re.sub("[() ]", "", col) for col in iris_df.columns]

In [20]:
print(sqldf("SELECT * FROM iris_df LIMIT 10;"))

   Petallength  PetalWidth  SepalLength  SepalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa
5          5.4         3.9          1.7         0.4  setosa
6          4.6         3.4          1.4         0.3  setosa
7          5.0         3.4          1.5         0.2  setosa
8          4.4         2.9          1.4         0.2  setosa
9          4.9         3.1          1.5         0.1  setosa

In [23]:
#Agrupar por agregacion promedio, minimo y máximo
#min
q = """
      select
        species
        , avg(SepalWidth)
        , min(SepalWidth)
        , max(SepalWidth)
      from
        iris_df
      group by
        species;
        
"""

## Project description
pysqldf le permite consultar pandas DataFrames utilizando la sintaxis SQL. Funciona de manera similar a sqldf en R. pysqldf busca proporcionar una forma más familiar de manipular y limpiar datos para personas nuevas en Python o pandas.

In [24]:
print("*" * 80)
print("aggregation")
print("-" * 80)
# Imprime q
print(q)
#promedio, min y máximp tres tipo de especies sectosa, versicolor, virginica
print(sqldf(q, locals()))
def pysqldf(q):
    "agregue esto a su script si se cansa de llamar a los locales ()"
    return sqldf(q, globals())
print("-" * 80)
print(q)
print(pysqldf(q))

********************************************************************************
aggregation
--------------------------------------------------------------------------------

      select
        species
        , avg(SepalWidth)
        , min(SepalWidth)
        , max(SepalWidth)
      from
        iris_df
      group by
        species;


      species  avg(SepalWidth)  min(SepalWidth)  max(SepalWidth)
0      setosa            0.246              0.1              0.6
1  versicolor            1.326              1.0              1.8
2   virginica            2.026              1.4              2.5
--------------------------------------------------------------------------------

      select
        species
        , avg(SepalWidth)
        , min(SepalWidth)
        , max(SepalWidth)
      from
        iris_df
      group by
        species;


      species  avg(SepalWidth)  min(SepalWidth)  max(SepalWidth)
0      setosa            0.246              0.1              0.6
1  versicolor            1.326              1.0              1.8
2   virginica            2.026              1.4              2.5

In [25]:
print(sqldf(q, locals()))

      species  avg(SepalWidth)  min(SepalWidth)  max(SepalWidth)
0      setosa            0.246              0.1              0.6
1  versicolor            1.326              1.0              1.8
2   virginica            2.026              1.4              2.5

In [26]:
print(sqldf(q, globals()))

      species  avg(SepalWidth)  min(SepalWidth)  max(SepalWidth)
0      setosa            0.246              0.1              0.6
1  versicolor            1.326              1.0              1.8
2   virginica            2.026              1.4              2.5

## #Inner Join

In [27]:
q = """
    select
        a.*
    from
        iris_df a
    inner join
        iris_df b
            on a.species = b.species
    limit 10;
"""
print("*" * 80)
print("joins")
print("-" * 80)
print(q)
print(pysqldf(q))

********************************************************************************
joins
--------------------------------------------------------------------------------

    select
        a.*
    from
        iris_df a
    inner join
        iris_df b
            on a.species = b.species
    limit 10;

   Petallength  PetalWidth  SepalLength  SepalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          5.1         3.5          1.4         0.2  setosa
2          5.1         3.5          1.4         0.2  setosa
3          5.1         3.5          1.4         0.2  setosa
4          5.1         3.5          1.4         0.2  setosa
5          5.1         3.5          1.4         0.2  setosa
6          5.1         3.5          1.4         0.2  setosa
7          5.1         3.5          1.4         0.2  setosa
8          5.1         3.5          1.4         0.2  setosa
9          5.1         3.5          1.4         0.2  setosa

## where

In [28]:
q = """
    select
        *
    from
        iris_df
    where
        species = 'virginica'
        and SepalLength > 7.7;
"""
print("*" * 80)
print("where clause")
print("-" * 80)
print(q)
print(pysqldf(q))
iris_df['id'] = range(len(iris_df))
q = """
    select
        *
    from
        iris_df
    where
        id in (select id from iris_df where SepalLength*SepalLength > 25);
"""
print("*" * 80)
print("subqueries")
print("-" * 80)
print(q)
print(pysqldf(q))

********************************************************************************
where clause
--------------------------------------------------------------------------------

    select
        *
    from
        iris_df
    where
        species = 'virginica'
        and SepalLength > 7.7;

Empty DataFrame
Columns: [Petallength, PetalWidth, SepalLength, SepalWidth, species]
Index: []
********************************************************************************
subqueries
--------------------------------------------------------------------------------

    select
        *
    from
        iris_df
    where
        id in (select id from iris_df where SepalLength*SepalLength > 25);

    Petallength  PetalWidth  SepalLength  SepalWidth     species   id
0           6.0         2.7          5.1         1.6  versicolor   83
1           6.3         3.3          6.0         2.5   virginica  100
2           5.8         2.7          5.1         1.9   virginica  101
3           7.1         3.0          5.9         2.1   virginica  102
4           6.3         2.9          5.6         1.8   virginica  103
5           6.5         3.0          5.8         2.2   virginica  104
6           7.6         3.0          6.6         2.1   virginica  105
7           7.3         2.9          6.3         1.8   virginica  107
8           6.7         2.5          5.8         1.8   virginica  108
9           7.2         3.6          6.1         2.5   virginica  109
10          6.5         3.2          5.1         2.0   virginica  110
11          6.4         2.7          5.3         1.9   virginica  111
12          6.8         3.0          5.5         2.1   virginica  112
13          5.8         2.8          5.1         2.4   virginica  114
14          6.4         3.2          5.3         2.3   virginica  115
15          6.5         3.0          5.5         1.8   virginica  116
16          7.7         3.8          6.7         2.2   virginica  117
17          7.7         2.6          6.9         2.3   virginica  118
18          6.9         3.2          5.7         2.3   virginica  120
19          7.7         2.8          6.7         2.0   virginica  122
20          6.7         3.3          5.7         2.1   virginica  124
21          7.2         3.2          6.0         1.8   virginica  125
22          6.4         2.8          5.6         2.1   virginica  128
23          7.2         3.0          5.8         1.6   virginica  129
24          7.4         2.8          6.1         1.9   virginica  130
25          7.9         3.8          6.4         2.0   virginica  131
26          6.4         2.8          5.6         2.2   virginica  132
27          6.3         2.8          5.1         1.5   virginica  133
28          6.1         2.6          5.6         1.4   virginica  134
29          7.7         3.0          6.1         2.3   virginica  135
30          6.3         3.4          5.6         2.4   virginica  136
31          6.4         3.1          5.5         1.8   virginica  137
32          6.9         3.1          5.4         2.1   virginica  139
33          6.7         3.1          5.6         2.4   virginica  140
34          6.9         3.1          5.1         2.3   virginica  141
35          5.8         2.7          5.1         1.9   virginica  142
36          6.8         3.2          5.9         2.3   virginica  143
37          6.7         3.3          5.7         2.5   virginica  144
38          6.7         3.0          5.2         2.3   virginica  145
39          6.5         3.0          5.2         2.0   virginica  147
40          6.2         3.4          5.4         2.3   virginica  148
41          5.9         3.0          5.1         1.8   virginica  149

## INNER JOIN

In [29]:
q = """
    SELECT
        m.*
        , b.births
    FROM
        meat m
    INNER JOIN
        births b
            on m.date = b.date
    ORDER BY
        m.date;
"""

print(pysqldf(q).head())

                         date    beef  veal    pork  lamb_and_mutton  \
0  1975-01-01 00:00:00.000000  2106.0  59.0  1114.0             36.0
1  1975-02-01 00:00:00.000000  1845.0  50.0   954.0             31.0
2  1975-03-01 00:00:00.000000  1891.0  57.0   976.0             35.0
3  1975-04-01 00:00:00.000000  1895.0  60.0  1100.0             34.0
4  1975-05-01 00:00:00.000000  1849.0  59.0   934.0             31.0

   broilers  other_chicken  turkey  births
0     646.2            NaN    64.9  265775
1     570.2            NaN    47.1  241045
2     616.6            NaN    54.4  268849
3     688.3            NaN    68.7  247455
4     690.1            NaN    81.9  254545